### ISSUE TITLE
Does sync support connecting to mysql through a unix socket?

### ISSUE THREAD

**Issue by Zankaria** [calzoneman/sync#986]
Does `sync` support connecting to mysql through a unix socket? The documentation on the configuration seems to imply no.

```
# MySQL server details
# server: domain or IP of MySQL server
# database: a MySQL database that the user specified has read/write access to
# user: username to authenticate as
# password: password for user
mysql:
  server: 'localhost'
  port: 3306
  database: 'cytube3'
  user: 'cytube3'
  password: ''
  pool-size: 10
```

If no, could it be implemented?
